---
apiVersion: bundle.gravitational.io/v2
kind: SystemApplication
metadata:
  name: cluster-ssl-app
  resourceVersion: 0.0.1
hooks:
  install:
    job: |
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: cluster-ssl-app-install
      spec:
        parallelism: 1
        completions: 1
        activeDeadlineSeconds: 600
        template:
          metadata:
            name: cluster-ssl-app-install
          spec:
            restartPolicy: Never
            hostNetwork: true
            containers:
              - name: install
                image: cluster-ssl-hook:latest
                args: ["install"]
  update:
    job: |
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: cluster-ssl-app-update
      spec:
        parallelism: 1
        completions: 1
        activeDeadlineSeconds: 600
        template:
          metadata:
            name: cluster-ssl-app-update
          spec:
            restartPolicy: Never
            hostNetwork: true
            containers:
              - name: update
                image: cluster-ssl-hook:latest
                args: ["update"]
  uninstall:
    job: |
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: cluster-ssl-app-uninstall
      spec:
        parallelism: 1
        completions: 1
        activeDeadlineSeconds: 600
        template:
          metadata:
            name: cluster-ssl-app-uninstall
          spec:
            restartPolicy: Never
            hostNetwork: true
            containers:
              - name: uninstall
                image: cluster-ssl-hook:latest
                args: ["uninstall"]
