---
apiVersion: bundle.gravitational.io/v2
kind: SystemApplication
metadata:
  name: cluster-ssl-app
  resourceVersion: 0.0.1
  namespace: default
hooks:
  install:
    job: |
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: cluster-ssl-app-install
        namespace: default
      spec:
        parallelism: 1
        completions: 1
        activeDeadlineSeconds: 600
        template:
          metadata:
            name: cluster-ssl-app-install
          spec:
            restartPolicy: OnFailure
            hostNetwork: true
            containers:
              - name: install
                image: quay.io/gravitational/debian-tall:buster
                command:
                  - |
                    helm3 install cluster-ssl /var/lib/gravity/resources/charts/cluster-ssl
  update:
    job: |
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: cluster-ssl-app-update
        namespace: default
      spec:
        parallelism: 1
        completions: 1
        activeDeadlineSeconds: 600
        template:
          metadata:
            name: cluster-ssl-app-update
          spec:
            restartPolicy: OnFailure
            hostNetwork: true
            containers:
              - name: update
                image: quay.io/gravitational/debian-tall:buster
                command:
                  - |
                    helm3 upgrade --install cluster-ssl /var/lib/gravity/resources/charts/cluster-ssl
  uninstall:
    job: |
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: cluster-ssl-app-uninstall
        namespace: default
      spec:
        parallelism: 1
        completions: 1
        activeDeadlineSeconds: 600
        template:
          metadata:
            name: cluster-ssl-app-uninstall
          spec:
            restartPolicy: OnFailure
            hostNetwork: true
            containers:
              - name: uninstall
                image: cluster-ssl-hook:latest
                args: ["uninstall"]
