{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "cluster-ssl-app.fullname" . }}
  labels:
    app: {{ template "cluster-ssl-app.name" . }}
    chart: {{ template "cluster-ssl-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    resourceNames:
      - privileged
    verbs:
      - use
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - create
    resourceNames:
      - cluster-ca
      - cluster-default-ssl
{{- end -}}
